### ISSUE TITLE
Post to Twitter:promptwars on every new game

### ISSUE THREAD

**Issue by netpoe** [aufacicenta/pulsemarkets#171]

**Comment by Udit-takkar** [comment]
@netpoe any more info about this issue?  do you want to see the share on twitter modal with some text about promptwars?

**Comment by netpoe** [comment]
> @netpoe any more info about this issue? do you want to see the share on twitter modal with some text about promptwars?

We need to revisit this one because Twitter (X) cancelled our account without notice. 

I think Mastodon.social would be another social network to post into. 

Or a subreddit: r/promptwars

**Comment by netpoe** [comment]
@Udit-takkar btw, have you played the game already? https://promptwars.xyz/

**Comment by Udit-takkar** [comment]
Yeah locally

**Comment by Udit-takkar** [comment]
>
> We need to revisit this one because Twitter (X) cancelled our account without notice.
> 
> I think Mastodon.social would be another social network to post into.
> 
> Or a subreddit: r/promptwars

is this issue still open?

**Comment by netpoe** [comment]
> > We need to revisit this one because Twitter (X) cancelled our account without notice.
> > I think Mastodon.social would be another social network to post into.
> > Or a subreddit: r/promptwars
> 
> is this issue still open? if it is can you tell me what exactly deliverable you want?

Our twitter account was blocked by X :/
So currently this issue is on-hold. I'll close it for now.
