### ISSUE TITLE
Migrate NEAR Rust Market contract to Arbitrum Stylus

### ISSUE THREAD

**Issue by netpoe** [aufacicenta/pulsemarkets#199]
Implement the Market contracts library in [Arbitrum Stylus](https://arbitrum.io/stylus)

A user should be able to play https://promptwars.xyz with a Metamask or any other EVM compatible wallet connected to the Arbitrum mainnet.

The current working contracts are these:

https://github.com/aufacicenta/pulsemarkets/tree/master/contracts/prompt-wars
https://github.com/aufacicenta/pulsemarkets/tree/master/contracts/market-factory

Basically, transpose them to use the Arbitrum Rust SDK so that the game can be played seamlessly in Arbitrum. 

## Motivation

Currently, https://promptwars.xyz/ is powered by NEAR Rust SDK smart-contracts. We want to move into Arbitrum smart-contracts to harness all EVM compatible wallets.

## How to get paid

Simply submit a PR with a working solution (including tests), and we'll transfer the money after merging into `master`. 

### Acceptance Criteria

- The source of truth are these tests: https://github.com/aufacicenta/pulsemarkets/blob/master/contracts/prompt-wars/src/tests.rs — The same must be implemented and must pass 100% in Arbitrum Stylus (Or Solidity)

## How to communicate with us?

Ask all the questions you want in the github comments of this issue. Or start a PR and we should talk about code 🤗

## Additional docs and resources

https://docs.promptwars.xyz/

**Comment by netpoe** [comment]
@mrkirthi-24 thanks for taking this challenge.
Let me know about your discoveries and any inquiries you may have 👍

**Comment by feliciien** [comment]
I would like to give a try to this one.

**Comment by mrkirthi-24** [comment]
I would like to withdraw myself from this issue. @feliciien you can please go ahead with it 👍

**Comment by netpoe** [comment]
cc @Udit-takkar this is the issue I mentioned on Linkedin. 

The Solidity ABI interface methods should be the same as in the Rust contracts, so that Typescript client implementation remains the same: https://github.com/aufacicenta/pulsemarkets/blob/master/app/src/providers/near/contracts/prompt-wars/contract.ts

**Comment by netpoe** [comment]
@feliciien any progress so far? You may push your progress for early reviewal. No strings attached.

**Comment by feliciien** [comment]
Hello I already implemented the
https://arbitrum.io/stylus
Contract but I have. To connect it to the pulse markets and do test
I’m also looking for the frontend page so I can add the logo  make it work.
Diouf

**Comment by feliciien** [comment]
And when I try to receive the fee token on the metamask nothing happens so
I can’t do appropriate test
I send them a mail but no response
Diouf

**Comment by feliciien** [comment]
today i want to rewrite the entire contract in Solidity. This involves defining the contract, functions, and data structures in Solidity syntax.

**Comment by netpoe** [comment]
> today i want to rewrite the entire contract in Solidity. This involves defining the contract, functions, and data structures in Solidity syntax. if I finish with that I will do a push for review.

Great. Yeah, Solidity will do best. Stylus is still in alpha, prob. not a good move...
