### ISSUE TITLE
Implement EVM wallet selector in Prompt Wars NavBar

### ISSUE THREAD

**Issue by netpoe** [aufacicenta/pulsemarkets#209]
The current NEAR wallet selector should be replaced by either a custom EVM wallet selector or one that's already  built. 

## BEFORE IMPLEMENTING

Please write down your plan for this. What packages are you planning to install. What selector, etc.
The design must follow the current guidelines and styles. 

Users must be able to connect any EVM compatible wallet extension (and/or) enter from a dApp browser, eg. Binance dApp Web3 wallet, or Metamask android app. 

**The selector must allow selecting different chains, eg. Ethereum, Optimisim, Arbitrum, etc...**

**The selector must show the current chain network, eg. Binance opChain testnet**

## How to get paid

A working implementation of the EVM compatible wallet selector. User should be able to sign any transaction inside the game dApp by using the selected wallet. 

The wallet MUST show the user's balance in the native coin of the selected chain AND the collateral token balance of the game.

### Submit a Pull Request

Maintainers will pull your changes before merging and test everything is working as expected. Note that other devs may work in this issue too. Quality is key.

**Comment by netpoe** [comment]
@Udit-takkar this is currently the top P1. Do you want to work on this one?
The Solidity transcription is done. Before we can integrate the new contracts, we need an EVM compatible wallet selector.

**Comment by netpoe** [comment]
@Ktoxcon this one is open for implementation and bounty, if you have the chance.

**Comment by Udit-takkar** [comment]
> @Udit-takkar this is currently the top P1. Do you want to work on this one? The Solidity transcription is done. Before we can integrate the new contracts, we need an EVM compatible wallet selector.

Okay, I was looking for some issues to work on this weekend. I can start with this

**Comment by Udit-takkar** [comment]
@netpoe I think we can use https://docs.walletconnect.com/web3modal/about 

<img width="1512" alt="Screenshot 2023-11-19 at 4 42 07 PM" src="https://github.com/aufacicenta/pulsemarkets/assets/53316345/82ee0226-df23-4063-9791-39dee2eb92d5">

<img width="1512" alt="Screenshot 2023-11-19 at 4 42 35 PM" src="https://github.com/aufacicenta/pulsemarkets/assets/53316345/44b2cbf2-8f19-4086-939e-0dddb53c1368">

**Comment by Udit-takkar** [comment]
Packages that i had to install

```
@web3modal/wagmi": "^3.3.2",
   "viem": "^1.19.3",
    "wagmi": "^1.4.7",
```
